### PR TITLE
Add Auth, Add Activity Controller, Fix SchedulingSession

### LINKED ISSUE #44: Setup Activities Controller

### LINKED ISSUE #54: Create Auth-Check Classes

### LINKED ISSUE #63: Fix SchedulingSession to pass build

### PR DESCRIPTION
**Pull request by Taremeh**
closes #44
closes #54 
closes #63 

Actually first build that is also able to run as an application 😅 ✅ 

- Fixed SchedulingSession Controller
- Added missing User getters & setters
- Added AuthenticationCheck and AuthorizedCheck methods
- Added ActivityController

### CODE REVIEW

File: src/main/java/ch/uzh/ifi/hase/soprafs21/service/ActivityService.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+import org.springframework.beans.factory.annotation.Qualifier;
+import org.springframework.stereotype.Service;
+import org.springframework.transaction.annotation.Transactional;
+
+import java.util.List;
+
+/**
+ * User Service
+ * This class is the "worker" and responsible for all functionality related to the user
+ * (e.g., it creates, modifies, deletes, finds). The result will be passed back to the caller.
```
Comment (Taremeh) [inline src/main/java/ch/uzh/ifi/hase/soprafs21/service/ActivityService.java]:
```suggestion
 * Activity Service.
```

File: src/main/java/ch/uzh/ifi/hase/soprafs21/controller/ActivityController.java [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+import ch.uzh.ifi.hase.soprafs21.rest.dto.UserPostDTO;
+import ch.uzh.ifi.hase.soprafs21.rest.mapper.DTOMapper;
+
+import java.util.List;
+
+
+/**
+ * User Controller
+ * This class is responsible for handling all REST request that are related to the user.
+ * The controller will receive the request and delegate the execution to the UserService and finally return the result.
```
Comment (Taremeh) [inline src/main/java/ch/uzh/ifi/hase/soprafs21/controller/ActivityController.java]:
```suggestion
 * Activity Controller
```

File: src/main/java/ch/uzh/ifi/hase/soprafs21/controller/ActivityController.java [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+    @ResponseStatus(HttpStatus.OK)
+    public void updateUserProfile(@RequestBody SwipeStatus swipeStatus, @PathVariable Long userId, @PathVariable Long activityId, @RequestHeader("Auth-Token")String token){
+
+        throw new UnsupportedOperationException("Not implemented yet");
+
+        // checks if user id and token are from the same user
+        //userService.authorizationCheck(userId, token);
+
+        // updates user profile
+        //userService.updateUserProfile(profileUpdates, userId);
```
Comment (Taremeh) [inline src/main/java/ch/uzh/ifi/hase/soprafs21/controller/ActivityController.java]:
```suggestion
```

**Comment by AleksandarRistic99** [comment]
looks good

**Review by AleksandarRistic99 — APPROVED** [review]
